# NumPy

## One dimensional array

In [1]:
import numpy as np
arr=np.array([10,20,25,40,60])

print(arr)

[10 20 25 40 60]


In [4]:
import numpy as np
a = [1, 2, 3, 4]
arr = np.array(a)
print("List in python : ", a)
print("Numpy Array in python :",
    arr)


List in python :  [1, 2, 3, 4]
Numpy Array in python : [1 2 3 4]


## Two dimensional array

In [2]:
import numpy as np
arr=np.array([
    [1,2,3],
    [7,5,9],
    [4,3,6]
])

print(arr)

[[1 2 3]
 [7 5 9]
 [4 3 6]]


In [6]:
import numpy as np
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
sample_array = np.array([list_1,
                        list_2,
                        list_3])
print("Numpy multi dimensional array in python\n",
    sample_array)


Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Shape

In [7]:
print("Shape of the array : ", sample_array.shape)

Shape of the array :  (3, 4)


## ways of creating numpy

In [8]:
import numpy as np

a=np.array([1,2,3])
b=np.array([[1,2],[3,4]])

## np.zeros()

In [9]:
a=np.zeros(3)
b=np.zeros((7,8))

## np.ones()

In [10]:
a=np.ones(6)
b=np.ones((3,4))

## np.linspace()

In [11]:
a=np.linspace(1,10,5)

## np.arange()

In [12]:
a=np.arange(1,10,2)
b=np.arange(1,10,3)

## np.full()

In [13]:
a=np.full(5, 99)
b=np.full((4,5), 99)